const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://media.istockphoto.com/id/161170090/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=8EctScsN7q5UmxeXPNBnYN1eFmJmgmp2bE0OIq_czwM=',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://media.istockphoto.com/id/1133287798/photo/romantic-dinner-for-two.jpg?s=612x612&w=0&k=20&c=f5tcMH2D_PDTHJAq2wCxVF8kk8m-J9TMbDLNI29Mk-s=',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://media.istockphoto.com/id/1291175021/photo/chocolate-milkshake.jpg?s=612x612&w=0&k=20&c=LkPVfYUcIdM85m9FI6QrAjXyzvOxrdhBEkmcPmlbTYw=',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://media.istockphoto.com/id/609831080/photo/cant-wait.jpg?s=612x612&w=0&k=20&c=_HNpsgzfuYabJPHtCkWlssNwExbnN7snXNBQyMMxKP8=',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://media.istockphoto.com/id/520889612/photo/boiled-eggs-in-bowl.jpg?s=612x612&w=0&k=20&c=wwes11nnPnZu7IFz6SSSjhsfoBK-ZcTFsqH9Em72ClA=',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://media.istockphoto.com/id/1133232638/photo/sandwich-black-cookie-consisting-of-two-chocolate-wafers-with-cream-filling-with-glass-of.jpg?s=612x612&w=0&k=20&c=7Oz6M44Ty4KN5SmOhIWYIHS9de7mu60rAwVBBhif_IA=',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://media.istockphoto.com/id/958245040/photo/bacon.jpg?s=612x612&w=0&k=20&c=840FRxvbCTbGCdWD5r5_SaxNkCW6E34z7yT6zY8Tev8=',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://media.istockphoto.com/id/854565540/photo/close-up-of-home-made-burgers.jpg?s=612x612&w=0&k=20&c=sbRJh-Y7hbQmwGuNCMWYgyFmxpkZc1Lrq0jzlnTLf4Q=',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://media.istockphoto.com/id/1222092193/photo/close-up-to-the-hands-of-two-caucasian-male-clashing-hands.jpg?s=612x612&w=0&k=20&c=enLUj2GQ_gaMj8YubAylSzCEUAy13ObLO0iINZqjMuQ=',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;